ci(goreleaser): Fix the failure of release workflow (#1263)
* ci(goreleaser): replace --rm-dist with --clean

--rm-dist was deprecated.

https://goreleaser.com/deprecations/?h=dep#-rm-dist

The release workflow failed.

https://github.com/projectdiscovery/naabu/actions/runs/11593776126/job/32278527815

```
/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser release -f .goreleaser/linux.yml --rm-dist
  ⨯ command failed                                   error=unknown flag: --rm-dist
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser' failed with exit code 1
```

* chore(goreleaser): set `version: 2`

Fix the warning.

```console
$ goreleaser check v2/.goreleaser/linux.yml
  • only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
  • checking                                 path=v2/.goreleaser/linux.yml
  • 1 configuration file(s) validated
  • thanks for using goreleaser!
```

* ci(goreleaser): replace --rm-dist with --clean